package com.example.balatropedia.ui.theme

import androidx.compose.ui.graphics.Color

val COLOR_BACKGROUND = Color(0xFF21252D)
val COLOR_HEADER = Color(0xFFAE3D33)

val COLOR_JOKER_BACKGROUND = Color(0xFF6D3B3B)
val COLOR_JOKER_TEXT = Color(0xFFFF8080)

val COLOR_MAZOS_BACKGROUND = Color(0xFF844A89)
val COLOR_MAZOS_TEXT = Color(0xFFED95F5)

val COLOR_VOUCHERS_BACKGROUND = Color(0xFF804855)
val COLOR_VOUCHERS_TEXT = Color(0xFFF3BAC8)

val COLOR_CONSUMIBLES_BACKGROUND = Color(0xFF806E4E)
val COLOR_CONSUMIBLES_TEXT = Color(0xFFDECAA6)

val COLOR_MANOS_BACKGROUND = Color(0xFF4C7D88)
val COLOR_MANOS_TEXT = Color(0xFF9DEBFD)

val COLOR_BOOSTER_BACKGROUND = Color(0xFF845845)
val COLOR_BOOSTER_TEXT = Color(0xFFFFAD8B)

val COLOR_BLINDS_BACKGROUND = Color(0xFF497447)
val COLOR_BLINDS_TEXT = Color(0xFFB3DEAB)

val COLOR_CHALLENGES_BACKGROUND = Color(0xFF3F3C66)
val COLOR_CHALLENGES_TEXT = Color(0xFFABADDE)

val COLOR_STAR = Color(0xFFC5A53F)